<a href="https://colab.research.google.com/github/koztigrkentavr/kalkulyator/blob/main/Pandas_Yakuniy_Amaliy_Vazifa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar!

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirdik`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va pandas kutubxonasini chop eting.

In [1]:
import pandas as pd

**2.** Versiya va konfiguratsiyani tekshiring.

In [2]:
pd.__version__

'2.2.2'

In [3]:
print(pd.__version__)

2.2.2


**3.** Pandas kutubxonasida mavjud bo'lgan barcha versiya ma'lumotlarini chop eting.

In [5]:
pd.show_versions()

/usr/local/lib/python3.11/dist-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(



INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.12.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.1.123+
Version               : #1 SMP PREEMPT_DYNAMIC Sun Mar 30 16:01:29 UTC 2025
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.3.5
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.4.0
html5lib              : 1.1
pymysql               : None
psyco

In [6]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints an

## `📌DataFrame: Asoslar`

DataFrames-da ma'lumotlarni tanlash(selecting), saralash(sorting), qo'shish(adding) va yig'ish(aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang:
``` python
import numpy as np
```

Quyidagi Python lug'ati(dictionary) `data` va Python ro'yxati(list) `labels` ni ko'rib chiqing:


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```



In [7]:
import numpy as np

In [9]:
data = {'animal': ['cat','cat','snake','dog','dog','cat','snake','cat','dog','dog'],
        'age': [2.5, 3, 0.5,np.nan,5,2,4.5,np.nan,7,3],
        'visits': [1,3,2,3,2,3,1,1,2,1],
        'priority':['yes','yes','no','yes','no','no','no','yes','no','no']}
labels = ['a','b','c','d','e','f','g','h','i','j']

**4.** Ushbu `lug'at`(dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [10]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)

In [11]:
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**5.** Ushbu DataFrame va uning ma'lumotlari haqidagi asosiy ma'lumotlarning qisqacha mazmunini ko'rsating.

`💡Ishora:` DataFrame-da chaqirilishi mumkin bo'lgan yagona usul mavjud.

In [13]:
print("DataFrame haqida qisqacha ma'lumotlar:")
print(df.info())

DataFrame haqida qisqacha ma'lumotlar:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes
None


**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [14]:
print("\nDastlabki 3 qator:")
print(df.head(3))


Dastlabki 3 qator:
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no


**7.** DataFrame `df`-dan faqat `animal` va `age` ustunlarini tanlang.

In [16]:
print("\n'animal' va 'age' ustunlari:")
print(df[['animal', 'age']])


'animal' va 'age' ustunlari:
  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0


**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi ma'lumotlarni tanlang.

In [18]:
print(df.loc[df.index[[3,4,8]],['animal','age']])

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0


**9.** Faqat `visits` soni 3 tadan ko'p bo'lgan qatorlarni tanlang.

In [20]:
print(df[df['visits'] > 3])

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []


10. Yosh yo'qolgan qatorlarni tanlang, ya'ni `NaN`

In [22]:
print(df[df['age'].isna()])

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik bo'lgan umumiy qatorlarni tanlang.

In [24]:
print(df[(df['animal'] == 'cat')  & (df['age'] < 3)])

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [25]:
#age 2 va 4 orasidagi qatorlar
print(df[df['age'].between(2,4)])

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no


**13.** `f` qatoridagi yoshni `1,5` ga o'zgartiring.

In [26]:
df.at['f','age'] = 1.5
print(df.loc['f'])

animal      cat
age         1.5
visits        3
priority     no
Name: f, dtype: object


**14.** `df` yordamida `visits` qatorining yig'indisini hisoblang.

In [27]:
print(df['visits'].sum())

19


**15.** Har bir `animal` uchun o'rtacha yoshni `df` da hisoblang.

In [28]:
print("\nHar bir hayvon turi uchun o'rtacha yosh:")
print(df.groupby('animal')['age'].mean())


Har bir hayvon turi uchun o'rtacha yosh:
animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64


**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [29]:
print(df['animal'].value_counts())

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64


**17.** `animal` ustunida, `snake` so'zini `python` so'ziga o'zgartiring.

In [30]:
df['animal'] = df['animal'].replace('snake','python')
print(df)

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no


## `📌DataFrame: Murakkab`

### Bir oz qiyinroq: to'g'ri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak bo'lishi mumkin

Oldingi bo'lim DataFrame-ning asosiy, ammo muhim operatsiyalari bo'yicha vazifalarni jamlagan edi. Quyida ma'lumotlarni kesishingiz kerak bo'lgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni o'z ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni o'z ichiga olgan ustun paydo bo'lishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [31]:
df = pd.DataFrame({'A':[1,2,2,3,4,5,5,5,6,7,7]})
df = df.drop_duplicates(subset='A')
print(df)

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7


In [33]:
np.unique_values =df['A'].unique()
np.unique_values.sort()
df_unique =pd.DataFrame({'A': np.unique_values})
print(df_unique)

   A
0  1
1  2
2  3
3  4
4  5
5  6
6  7


**19.** Raqamli qiymatlardan iborat DataFrame berildi

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 o'lchovi
```

Qatordagi har bir elementdan satrning o'rtacha qiymatini qanday ayirish mumkin?

In [35]:
df = pd.DataFrame(np.random.random(size=(5,3)))
df_nat = df.sub(df.mean(axis=1), axis=0)
print(df_nat)

          0         1         2
0 -0.077378  0.253394 -0.176016
1 -0.342671  0.465844 -0.123173
2 -0.100148 -0.346525  0.446673
3  0.126522  0.067417 -0.193939
4  0.084355 -0.126252  0.041897


**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yig'indisi eng kichik ekanini hisoblang. U ustunning yorlig'ini qaytaring.

In [39]:
df =pd.DataFrame(np.random.random(size=(5,10)),columns=list('abcdefghij'))
columns_sums = df.sum()# Har bir ustun yig'indisi
min_sum_column = columns_sums.idxmin()# Eng kichik yig'indiga ega ustun
print(min_sum_column)

e


**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrame ning har bir qatori uchun uchinchi `NaN` qiymatini o'z ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [42]:
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data,columns=columns)

# Javobni bu yerga yozing!
def top_uch_nan(row):
  return row.index[row.isna().cumsum() == 3][0]
result = df.apply(top_uch_nan, axis=1)
print(result.tolist())

['e', 'c', 'd', 'h', 'd']


**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [43]:
# Javobni bu yerga yozing!
df = pd.DataFrame({
    'grps':list('aaabbcaabcccbbc'),
    'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]
})
result = df.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum())
print(result)


grps
a    409
b    156
c    345
Name: vals, dtype: int64


**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega 'A' va 'B'. "A" dagi qiymatlar 1 dan 100 gacha (shu jumladan).

“A” dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yig'indisini hisoblang.

Javob quyidagicha bo'lishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [72]:
import numpy as np
import pandas as pd

In [73]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# Javobni bu yerga yozing!
df['A_bin'] = pd.cut(df['A'],bins = [0,10,20,30,40,50,60,70,80,90,100])
result = df.groupby('A_bin')['B'].sum()
print(result)

A_bin
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64


<ipython-input-73-f62f6247833c>:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby('A_bin')['B'].sum()


**24.** 'X' butun son ustuni bo'lgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha bo'lishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [74]:
#javobni bu yerga yozing!
df = pd.DataFrame({'X': [7,2,0,3,4,2,5,0,3,4]})
last_zero_idx = -1
output = []
for i, val in enumerate(df['X']):
  if val == 0:
    last_zero_idx = i
    output.append(0)
  else:
      output.append(i - last_zero_idx)
df['Y']=output
print(df)

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2


##`📌Ma'lumotlarni tozalash`

Bu har doim sodir bo'ladi: kimdir sizga noto'g'ri tuzilgan satrlar, ro'yxatlar va yetishmayotgan ma'lumotlarni o'z ichiga olgan ma'lumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan so'ng u quyidagi ko'rinishga ega bo'lishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


In [75]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan,10065,np.nan,10085],
              'RecentDelays': [[23,47],[], [24,43,87], [13], [67,32]],
                    'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways.)',
                                '12.Air France', '"Swiss Air"']})

In [76]:
print(df)

            From_To  FlightNumber  RecentDelays             Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM(!)
1      MAdrid_miLAN           NaN            []   <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways.)
3    Budapest_PaRis           NaN          [13]       12.Air France
4   Brussels_londOn       10085.0      [67, 32]         "Swiss Air"


**26.** **FlightNumber** ustunidagi ba'zi qiymatlar yo'q. Ular `NaN` ko'rinishida yozilgan. Bu raqamlar har bir qatorda 10 ga ko'payishi kerak, shuning uchun 10055 va 10075 ni qo'yish kerak. Ushbu yetishmayotgan raqamlarni to'ldirish uchun `df` ni o'zgartiring va ustunni butun son ustuniga aylantiring.

In [77]:
df['FlightNumber']= df['FlightNumber'].interpolate().astype(int)
print(df)

            From_To  FlightNumber  RecentDelays             Airline
0      LoNDon_paris         10045      [23, 47]              KLM(!)
1      MAdrid_miLAN         10055            []   <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways.)
3    Budapest_PaRis         10075          [13]       12.Air France
4   Brussels_londOn         10085      [67, 32]         "Swiss Air"


**27.** **From\_To** ustunini ikkita alohida ustun ko'rinishida yozing.                                          

To'g'ri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [78]:
temp = df['From_To'].str.split('_', expand=True)
temp.columns = ['From', 'To']
print(temp)

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" bo'lishi kerak.)

In [79]:
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()
print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ʻ'(British Airways. )'' `British Airways` ko'rinishida yozilishi kerak.

In [80]:
import numpy as np
import pandas as pd
import re

In [62]:
df['Airline'] = df['Airline'].str.replace(r'[^a-zA-Z\s]','', regex=True)# Faqat harflar va bo'shliq qoldiriladi
df['Airline'] = df['Airline'].str.replace(r'^\d+\.\s*','',regex = True)#Boshlanishidagiraqam va nuqtani olib tashlash
df['Airline'] = df['Airline'].str.strip()#Bo'shliqlarni olib tashlash
print(df['Airline'])

0                KLM
1         Air France
2    British Airways
3         Air France
4          Swiss Air
Name: Airline, dtype: object


**30.** `df` dan **From_To** ustunini o'chiring va Temporary DataFrame `temp` ustunini qo'shing.

In [81]:
df = df.drop('From_To', axis=1)
df = pd.concat([df,temp], axis=1)
print(df)

   FlightNumber  RecentDelays             Airline      From         To
0         10045      [23, 47]              KLM(!)    London      Paris
1         10055            []   <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways.)    London  Stockholm
3         10075          [13]       12.Air France  Budapest      Paris
4         10085      [67, 32]         "Swiss Air"  Brussels     London


**31**. `RecentDelays` ustunida qiymatlar DataFrame-ga ro'yxat sifatida kiritilgan. Sizning vazifangiz birinchi qiymatni o'z ustunida, har bir ikkinchi qiymatni o'z ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat bo'lmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi ko'rinishda bo'lishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [82]:
delays = df['RecentDelays'].apply(pd.Series)
delays.columns = [f'delay_{i+1}' for i in range(delays.shape[1])]
df = df.drop('RecentDelays', axis=1)
df = pd.concat([df,delays],axis=1)
print(df)

   FlightNumber             Airline      From         To  delay_1  delay_2  \
0         10045              KLM(!)    London      Paris     23.0     47.0   
1         10055   <Air France> (12)    Madrid      Milan      NaN      NaN   
2         10065  (British Airways.)    London  Stockholm     24.0     43.0   
3         10075       12.Air France  Budapest      Paris     13.0      NaN   
4         10085         "Swiss Air"  Brussels     London     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN  


##`📌Minesweeper`


### Minesweeper tarmog'ida xavfsiz kvadratlar uchun raqamlar yaratamiz!

💡 Agar siz Windowsning avvalgi versiyalaridan foydalangan bo'lsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz o'yin bilan tanish bo'lmasangiz, kvadratchalar to'plamini tasavvur qiling: bu kvadratlarning ba'zilari mineni yashiradi. Agar siz mineni bossangiz, darhol yo'qotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qo'shni bo'lgan kvadratchalarda qancha mine borligini ko'rsatadigan raqamni ko'rasiz. O'yinning maqsadi to'rdagi mine bo'lmagan barcha kvadratlarni ochishdir.

Ushbu bo'limda biz Minesweeper o'yini uchun kerakli ma'lumotlarni o'z ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qo'shni kvadratlarda topilgan minelar sonini aniqlaymiz!

**32**. Tasavvur qiling, biz Minesweeper o'yinini 5 dan 4 gacha bo'lgan panjarada o'ynayapmiz, ya'ni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani o'z ichiga olgan `'x'` va `'y'`. Ya'ni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [86]:
X,Y = 5,4
df = pd.DataFrame([(x,y) for y in range(Y)for x in range(X)],columns=['x','y'])
print(df)


    x  y
0   0  0
1   1  0
2   2  0
3   3  0
4   4  0
5   0  1
6   1  1
7   2  1
8   3  1
9   4  1
10  0  2
11  1  2
12  2  2
13  3  2
14  4  2
15  0  3
16  1  3
17  2  3
18  3  3
19  4  3


**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir bo'lish ehtimoli 0,4 bo'lishi kerak.

In [89]:
np.random.seed(0)
df['mine']=np.random.choice([0,1], size=len(df), p=[0.6,0.4])
def get_adjacent_mine_count(row,df):
  x,y = row['x'],row['y']
  neighbors = [(x+i,y+i) for i in [-1,0,1] for j in [-1,0,1]if not (i==0 and j==0)]
  count = 0
  for nx, ny in neighbors:
    if ((df['x']==nx)& (df['y']==ny)).any():
      count +=df[(df['x']==nx) & (df['y']==ny)]['mine'].values[0]
      return count
df['adjacent'] = df.apply(lambda row: get_adjacent_mine_count(row,df),axis=1)
print(df)

    x  y  mine  adjacent
0   0  0     0         0
1   1  0     1         1
2   2  0     1         1
3   3  0     0         0
4   4  0     0         0
5   0  1     1         1
6   1  1     0         0
7   2  1     1         1
8   3  1     1         1
9   4  1     0         0
10  0  2     1         1
11  1  2     0         1
12  2  2     0         0
13  3  2     1         1
14  4  2     0         1
15  0  3     0         0
16  1  3     0         1
17  2  3     1         0
18  3  3     1         0
19  4  3     1         1


 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qo'shni kvadratlarda topilgan minelar soni bo'lishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv bo'lgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [101]:
def get_adjacent_mine_count(row,df):
  x,y = row['x'],row['x']
  neighbors = [(x+i,y+j)for i in[-1,0,1] for j in [-1,0,1] if not (i==0 and j==0)]
  count = 0
  for nx, ny in neighbors:
      if ((df['x']==nx) & (df['y'] == ny)).any():
        count += df[(df['x'] == nx) & (df['y']==ny)]['mine'].values[0]
  return count
df['adjacent'] = df.apply(lambda row:get_adjacent_mine_count(row,df), axis=1)
print(df)

    x  y  mine  adjacent
0   0  0     0         2
1   1  0     1         5
2   2  0     1         5
3   3  0     0         3
4   4  0     0         2
5   0  1     1         2
6   1  1     0         5
7   2  1     1         5
8   3  1     1         3
9   4  1     0         2
10  0  2     1         2
11  1  2     0         5
12  2  2     0         5
13  3  2     1         3
14  4  2     0         2
15  0  3     0         2
16  1  3     0         5
17  2  3     1         5
18  3  3     1         3
19  4  3     1         2


**35**. Mineni o'z ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga o'zgartiring.

In [102]:
df.loc[df['mine'] == 1, 'adjacent'] = np.nan
print(df)

    x  y  mine  adjacent
0   0  0     0       2.0
1   1  0     1       NaN
2   2  0     1       NaN
3   3  0     0       3.0
4   4  0     0       2.0
5   0  1     1       NaN
6   1  1     0       5.0
7   2  1     1       NaN
8   3  1     1       NaN
9   4  1     0       2.0
10  0  2     1       NaN
11  1  2     0       5.0
12  2  2     0       5.0
13  3  2     1       NaN
14  4  2     0       2.0
15  0  3     0       2.0
16  1  3     0       5.0
17  2  3     1       NaN
18  3  3     1       NaN
19  4  3     1       NaN


**36**. DataFrame-ni `adjacent` minelar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [104]:
pivot = df.pivot(index = 'y', columns ='x', values='adjacent')
print(df)

    x  y  mine  adjacent
0   0  0     0       2.0
1   1  0     1       NaN
2   2  0     1       NaN
3   3  0     0       3.0
4   4  0     0       2.0
5   0  1     1       NaN
6   1  1     0       5.0
7   2  1     1       NaN
8   3  1     1       NaN
9   4  1     0       2.0
10  0  2     1       NaN
11  1  2     0       5.0
12  2  2     0       5.0
13  3  2     1       NaN
14  4  2     0       2.0
15  0  3     0       2.0
16  1  3     0       5.0
17  2  3     1       NaN
18  3  3     1       NaN
19  4  3     1       NaN


##📌BONUS!

O'zingiz javob berishni istagan savolni kiriting va unga javob bering!